### ISSUE TITLE
Unable to login/refresh permissions

### ISSUE THREAD

**Issue by FelixGail** [BjoernPetersen/JMusicBot-desktop#30]
Log: https://gist.github.com/FelixGail/5207faf4576df97eed704fe56880275c

Users are unable to login. Error are consistent after restart and even after deleting secrets, config and user db.

**Comment by BjoernPetersen** [comment]
Could you try again with this version? https://circleci.com/gh/BjoernPetersen/JMusicBot-desktop/177#artifacts/containers/0

Also, what Java version and what build are you using (OpenJDK, OracleJDK, ...)?

**Comment by FelixGail** [comment]
It took some time, but the new version works
